### ISSUE TITLE
uBlock Originのフィルターのスニペットなどを復活させるか判断して実装する

### ISSUE THREAD

**Issue by ncaq** [ncaq/uBlacklistRule#10]
[uBlock Origin向けのフィルターをダイエットする · Issue #7 · ncaq/uBlacklistRule](https://github.com/ncaq/uBlacklistRule/issues/7)
で指摘された、

>  なお後者2つはGoogle Search Fixer有効がメインの環境なら必要です。たまに現れるFeatured SnippetsとPeople also askを消しています。

に対応。

今の所使ってみてどれぐらいうざいか分かってないのでフィルターを膨らませて対処するか迷い中です。

**Comment by hirorpt** [comment]
[私のフィルタ](https://github.com/hirorpt/ubo-stackoverflow-translation/blob/master/.github/workflows/generate-files.yml#L38-L67)では他に画像検索も消すルールが入っています。とはいえ必要になることはまずないでしょう。
uBlacklistは消していて、また消しても[arosh/ublacklist-stackoverflow-translation](https://github.com/arosh/ublacklist-stackoverflow-translation)のドメイン数では体感できる重さの違いが生じなかったために入れているだけです。

**Comment by ncaq** [comment]
これ書いた当初は、
[uBlacklistRule/uBlockOrigin.txt at master · ncaq/uBlacklistRule](https://github.com/ncaq/uBlacklistRule/blob/master/uBlockOrigin.txt)
がどれぐらいの長さになるのか判別しきれなかったからこういう書き方になりましたが、
現在600行ぐらいで収まるならあっても良さそうですね
