### ISSUE TITLE
github co(github.blogコピーサイト)追加依頼

### ISSUE THREAD

**Issue by DaisukeDaisuke** [ncaq/uBlacklistRule#17]
- `github.co`: `github.blog`, `github.com`のコピーサイトと推測します(タイポスクワッティング)
github.com内のタイポと思われるリンクより検出
https://www.google.com/search?q=site%3Agithub.co

**Comment by ncaq** [comment]
これなんで閉じたんですか?
本物にリダイレクトされるから予約してたって感じですかね?

**Comment by DaisukeDaisuke** [comment]
さらに調査した結果、bitlyの独自ドメインへリンクである事は判明し、コピーサイトではないと断定しました為、このissueを閉じさせていただきました。
私の勘違いにより、ご迷惑をおかけした事をお詫び申し上げます。
↓bitlyのロゴ表示
https://github.co/a

**Comment by ncaq** [comment]
承知しました、コントリビュートありがとうございます。
