### ISSUE TITLE
変換ツール部分の説明を追加して欲しい

### ISSUE THREAD

**Issue by Chamiu** [ncaq/uBlacklistRule#23]
uBlacklistのfilterからuBlock Originのfilterへの変換ツール部分の使い方を教えてください。
当方もuBlacklistのfilterを作成しており、uBlock OriginではなくAdGuardを使用していますが、この変換をtext editorの置換機能でやると副作用が多いので...

**Comment by ncaq** [comment]
ここの部分ですか。
<https://github.com/ncaq/uBlacklistRule/blob/8a9a90578a1d63c8699112dc15e40ba66e4a004e/src/UBlockOrigin.hs#L30>
単にホストのリストを収集して、テキスト合成して出しているだけです。

**Comment by Chamiu** [comment]
> Haskellプログラムでデータを生成する
を見逃していました。
