### ISSUE TITLE
追加依頼 br.atsit.in

### ISSUE THREAD

**Issue by thr3a** [ncaq/uBlacklistRule#32]
# 本家URL

https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-Drops-Swap-Kill

# コピーURL

https://br.atsit.in/ja/?p=319678

翻訳されてますが、Phoronixとの繋がりが見えなかったので技術系スパムサイトと思われます。

**Comment by ncaq** [comment]
機械翻訳なのは分かってましたが、オリジナルは自分で書いてるのかなあと思ってました。
報告ありがとうございます。
