### ISSUE TITLE
追加依頼 super-unix.com

### ISSUE THREAD

**Issue by thr3a** [ncaq/uBlacklistRule#34]
# 本家URL

- https://askubuntu.com/questions/574110/how-to-use-ecryptfs-with-a-non-home-directory

# コピペURL

- https://super-unix.com/ubuntu/ubuntu-how-to-use-ecryptfs-with-a-non-home-directory/

技術系コピペサイトかと思われます。

**Comment by ncaq** [comment]
そのURL自体にはアクセスが出来ませんでしたが、同じドメインの他のページが明らかにコピペなことを確認しました。
報告に感謝。
