### ISSUE TITLE
uBlock Origin向けのルールも生成する

### ISSUE THREAD

**Issue by ncaq** [ncaq/uBlacklistRule#5]
Firefox for AndroidにすぐにuBlacklistも戻るだろうと思っていましたが、
思ったより長引きそうなので。
他のアドブロック系ツールがあるプラットフォームで広く使えるかもしれません。

**Comment by hirorpt** [comment]
参考まで
https://github.com/arosh/ublacklist-stackoverflow-translation/issues/76

**Comment by ncaq** [comment]
@hirorpt ありがとうございます!参考にします!
