### ISSUE TITLE
uBlock Origin向けのフィルターをダイエットする

### ISSUE THREAD

**Issue by ncaq** [ncaq/uBlacklistRule#7]
[uBlock Origin向けのルールも生成する · Issue #5 · ncaq/uBlacklistRule](https://github.com/ncaq/uBlacklistRule/issues/5)
は一応ルールを生成したので閉じました。
しかしこのルールには問題があり、
ルールが2万行ぐらいになるからか、
Google検索がとても重くなります。
コンテンツスクリプトの方で動かしてるのかな?デスクトップPCでモバイルエミュレートしても重いぐらいですし、スマートフォンではめっちゃカクつきます。
フィルターのダイエットが必要でしょう。

**Comment by ncaq** [comment]
すぐに思いつく改善案はいくつかあります。
1. 除いても問題のないルールを見つける
2. 実在しないホストを除外する
3. uBlock Originの除外機構が遅いのは諦めて、機械生成部分はある程度妥協してこちらには入れない

**Comment by hirorpt** [comment]
uBlacklistと異なり単に部分一致させているだけなので、TLDの自動生成は完全に不要ではないでしょうか (もし必要なら正規表現も書けます)。
なお後者2つはGoogle Search Fixer有効がメインの環境なら必要です。たまに現れるFeatured SnippetsとPeople also askを消しています。

**Comment by ncaq** [comment]
作業あらかた終わってからコメントに気がついた…

> uBlacklistと異なり単に部分一致させているだけなので、TLDの自動生成は完全に不要ではないでしょうか (もし必要なら正規表現も書けます)。
たしかに…

>  なお後者2つはGoogle Search Fixer有効がメインの環境なら必要です。たまに現れるFeatured SnippetsとPeople also askを消しています。
エミュレータで適当に見て後者2つがヒットしなかったので要らないのかと思ってしまいました。
そういうことだったんですね。
